name: nav
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:

   - images\Logo.png
   - images\appbar.png
   - images\notf.png
   - images\banner.png
   - images\border.png
   - images\plant1.png
   - images\plant2.png
   - images\plant4.png
   - images\plant5.png
   - images\plant6.png
   - images\plant7.png
   - icons\mart_icon.png
   - icons\dog_icon.png
   - icons\border.png
   - icons\home_icon.png
   - icons\shoping_icon.png
   - icons\profile_icon.png

  